# Generated by Django 4.1.7 on 2023-03-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Treatment', max_length=200, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.DurationField(default='00:15')),
                ('description', models.CharField(default='This is the description of the treatment.', max_length=500)),
            ],
        ),
    ]
