# Generated by Django 4.1.7 on 2023-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_treatment_active_alter_treatment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='client_count',
            field=models.IntegerField(default=1),
        ),
    ]
