# Generated by Django 4.2.1 on 2023-05-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_clientsettings_clientsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsetting",
            name="company_name_slug",
            field=models.SlugField(
                default=models.CharField(max_length=150, unique=True), max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="clientsetting",
            name="company_name",
            field=models.CharField(max_length=150),
        ),
    ]
