# Generated by Django 4.2.1 on 2023-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientsetting_company_name_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsetting',
            name='company_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='company_name_slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', editable=False, max_length=150, unique=True),
        ),
    ]
