# Generated by Django 4.2.1 on 2023-06-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clientsetting_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='calendar_email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='clientsetting',
            name='calendar_id',
            field=models.CharField(default='email@example.com', max_length=90),
            preserve_default=False,
        ),
    ]
